config/routes.rb
Escuela::Application.routes.draw do


  resources :ubicaciones

  resources :cursos do
  resources :estudiantes
  end
  get "pages/index"
  resources :studiantes
  resources :curso
  resources :pages
  resources :estudiante
  resources :horarios
  resources :materias
  resources :instructores
  root :to => 'pages#index'


 
end

app/models/horario.rb
class Horario < ActiveRecord::Base
  attr_accessible :aula, :fecha, :hora, :materia_id, :curso_id, :instructor_id, :job_horario_no
  belongs_to :materia
  belongs_to :curso
  belongs_to :instructor

   
  def self.search(search)
		where('aula like ?', "%#{search}%")
	end
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  require 'prawn'

  helper_method :sort_column, :sort_direction

  def index
    
     @horarios = Horario.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(2)

     respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @horarios }
    end
  
  end
  
  def show
      #@horario = Horario.find(params[:id])
       #pdf = Prawn::Document.new
       #send_data pdf.render, :filename => "Horarios de aprendizes", :type => "application/pdf"
      @horario = Horario.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @horario }
      format.pdf do
        pdf = HorarioPdf.new(@horario, view_context)
        send_data pdf.render, filename:
        "Horario_#{@horario.job_horario_no}.pdf",
        type: "application/pdf"
      end
      end
  end
 
 
 

  def new
      @horario = Horario.new
  end

  def edit
      @horario = Horario.find(params[:id])
  end

  def create
      @horario = Horario.new(params[:horario])
      render :action => :new unless @horario.save
  end

  def update
      @horario = Horario.find(params[:id])
      render :action => :edit unless @horario.update_attributes(params[:horario])
  end

  def destroy
      @horario = Horario.find(params[:id])
      @horario.destroy
  end


  private

  def sort_column

   Horario.column_names.include?(params[:sort]) ? params[:sort] : "aula"
    
  end

  def sort_direction 

    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    
  end
  
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/views/horarios/_form.html.erb
<%= simple_form_for(@horario, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

    <%= f.error_notification %>
    <%= display_base_errors @horario %>
    <%= f.input :hora %>
    <%= f.input :aula %>
    <p>
     <%= f.input :fecha %>
    </p>
    <p>
      <%= f.label :curso_id %>
      <%= f.collection_select :curso_id, Curso.all, :id, :nombre, prompt: "Selecione Curso"  %>
    </p>
    <p>
      <%= f.label :instructor_id %>
      <%= f.collection_select :instructor_id, Instructor.all, :id, :nombre, prompt: "Selecione Instructor"  %>
    </p>
    <p>
      <%= f.label :materia_id %>
      <%= f.collection_select :materia_id, Materia.all, :id, :nombre, prompt: "Selecione Materias"  %>
    </p>
    <div class="form-actions">
        <%= f.submit "guardar", :class => 'btn btn-primary' %>
        <%= link_to 'Atras', horarios_path, :class => 'btn btn-small' %>
    </div>
<% end %>

app/views/horarios/_horario.html.erb
<tr id=<%= "horario_#{horario.id}" %>
  <td></td>
  <td><%= link_to horario.id, edit_horario_path(horario), :remote => true %></td>
  <td><%= horario.fecha %></td>
  <td><%= horario.hora %></td>
  <td><%= horario.aula %></td>
  <td><%= horario.curso_id %></td>
  <td><%= horario.instructor_id %></td>
  <td><%= horario.materia.nombre %></td>
  <td><%= link_to image_tag("pdf1.png"), horario_path(horario, :format => "pdf") %></td>
  <td>
  <%= link_to  image_tag('mostrar.png'), horario,     :remote => true, :class => 'btn btn-mini' %>

    <%= link_to image_tag('editar1.png', :title => "Editar Equipos"), edit_horario_path(horario),  :remote => true,
        :class => 'btn btn-mini'%>
    <%= link_to image_tag('eliminar.png', :title => "Eliminar Equipos"), horario, :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>
       
  </td>
</tr>
  
      
        
            
<p>
  Download:
  <%= link_to "Excel", horarios_path(format: "xls") %>
</p>         
              
       

app/views/horarios/_show.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
  <p><b>Id:</b> <%= @horario.id %></p>
  <p><b>Fecha:</b> <%= @horario.fecha %></p>
  <p><b>Hora:</b> <%= @horario.hora %></p>
  <p><b>Aula:</b> <%= @horario.aula %></p>
  <p><b>Curso:</b> <%= @horario.curso_id %></p>
  <p><b>Instructor:</b> <%= @horario.instructor_id %></p>
  <p><b>Materia:</b> <%= @horario.materia_id %></p>

    
   
 


</div>

app/views/horarios/create.js.erb
$('table tbody').append("<%= escape_javascript(render @horario) %>")
$.lazybox.close()

app/views/horarios/destroy.js.erb
$("table tr#horario_<%= @horario.id %>").remove();

app/views/horarios/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/horarios/index.html.erb
<%- model_class = Horario -%>
<div class="page-header">
  <h1><%= link_to image_tag("universidad.png")%><i>Horarios</i></h1>
</div>
<div class="row">
  <div class="span4">
    <%= form_tag request.path, :class => 'form-vertical', :method => 'get' do %>
      <%= content_tag :label, :class => 'control-label' do %>
      <h4>Bucar Horarios</h4>
          <%= text_field_tag :search, params[:search], :class => 'text_field' %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium', :name => nil %>
          <%= content_tag :label, :class => 'control-label' do %>
      <h4>Registros Mostrar</h4>
          <%= text_field_tag :registro, params[:registro], :class => 'text_field'  %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium'  %>
    </div>
    <% end %>
   <% end %>
  <% end %>   
</div>
<table class="table table-bordered pretty">

  <thead>
    <tr >
      <th><%= sortable "id" %></th>
      <th>Fecha</th>
      <th>Hora</th>
       <th>Aula</th>
       <th>Curso</th>
       <th>Instructor</th>
       <th>materia</th>
    </tr>
  </thead>
  <tbody>
     <%= render @horarios %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to image_tag('nuevo.png', :tile  => "Mostrar Equipos"),  new_horario_path,  :remote => true %></td>
   
    </tr>
  </tfoot>
  <tfoot>
    <tr>
      <td>
    <b>Total Horarios</b>
  </td>
    <td>
    <%= @horarios.total_entries %>
  </td>
    </tr>
  </tfoot>
</table>
</div>

   <br />
  <br />
  <div align="center">
    <div class="pagination">
    </ul>
    <%= will_paginate @horarios, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  </div>
</div>

app/views/horarios/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">aula</Data></Cell>
      </Row>
    <% @horarios.each do |horario| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= horario.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= horario.aula %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/horarios/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/horarios/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})
$('#horarios').tooltip('show')

app/views/horarios/update.js.erb
$('tr#horario_<%= @horario.id %>').replaceWith("<%= escape_javascript(render @horario) %>")
$.lazybox.close()