config/routes.rb
Escuela::Application.routes.draw do


  resources :ubicaciones

  resources :cursos do
  resources :estudiantes
  end
  get "pages/index"
  resources :studiantes
  resources :curso
  resources :pages
  resources :estudiante
  resources :horarios
  resources :materias
  resources :instructores
  root :to => 'pages#index'


 
end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :instructor
  has_many :estudiante
  attr_accessible :ficha, :nombre, :instructor_id

   validates :nombre, :presence => true, :length => { :maximum => 50 }
    validates :ficha, :presence => true, :length => { :maximum => 6 }


  def self.search(search)
		where('nombre like ?', "%#{search}%")
	end

 
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController

    helper_method :sort_column, :sort_direction
    before_filter :find_curso, :except => [ :index, :create, :new ]

  def index
      
      @cursos = Curso.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(2)
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cursos }
      
    end
  end

  def show
  end

  def new
      @curso = Curso.new
  end

  def edit
      
  end

  def create

      @curso = Curso.new(params[:curso])
      render :action => :new unless @curso.save
  end

  def update
      
      render :action => :edit unless @curso.update_attributes(params[:curso])
  end

  def destroy
    
      @curso.destroy
  end

  private

  def find_curso
      @curso = Curso.find(params[:id]) if params[:id]
  end


  private

  def sort_column

   Curso.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
    
  end

  def sort_direction 

    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    
  end
  
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_curso.html.erb
<tr id=<%= "curso_#{curso.id}" %>>  <td><%= link_to curso.id %></td>  <td><%= curso.nombre %></td>  <td><%= curso.ficha %></td>  <td><%= curso.instructor_id %></td>    <td>    <%= link_to  image_tag('mostrar.png', :title => "mostrar"), curso,     :remote => true, :class => 'btn btn-mini' %>    <%= link_to image_tag('editar1.png', :title => "Editar"), edit_curso_path(curso),  :remote => true,        :class => 'btn btn-mini'%>    <%= link_to image_tag('eliminar.png', :title => "Eliminar"), curso, :data => { :confirm => 'Esta Seguro?' },        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %>  <td><%= link_to image_tag('miembros.png', :tile => "Agregar cursos"), curso_estudiantes_path(curso) %></td>         </td>  <td>  <%= link_to 'Export XLS', url_for(:format => 'xls') %></td></tr>                                    

app/views/cursos/_form.html.erb
<%= simple_form_for(@curso, :html => { :class => 'form-horizontal' }, :remote => true) do |f| %>

  	<%= f.error_notification %>
  	<%= display_base_errors @curso %>
	<%= f.input :nombre %>
 	<%= f.input :ficha %>
 	
 	<p>
      <%= f.label :instructor_id %>
      <%= f.collection_select :instructor_id, Instructor.all, :id, :nombre, prompt: "Selecione Instructor"  %>
    </p>
  	
  	<div class="form-actions">
	    <%= f.submit "guardar", :class => 'btn btn-primary' %>
	    <%= link_to 'Atras', cursos_path, :class => 'btn btn-small' %>
  	</div>
<% end %>

app/views/cursos/_show.html.erb
<%- model_class = Curso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
  <p><b>Id:</b> <%= @curso.id %></p>
  <p><b>Nombre:</b> <%= @curso.nombre %></p>
  <p><b>Ficha:</b> <%= @curso.ficha %></p>
  <p><b>Instructor:</b> <%= @curso.instructor_id %></p>
   
</div>

app/views/cursos/create.js.erb
$('table tbody').append("<%= escape_javascript(render @curso) %>")
$.lazybox.close()

app/views/cursos/destroy.js.erb
$("table tr#curso_<%= @curso.id %>").remove();

app/views/cursos/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/cursos/index.html.erb
<%- model_class = Curso -%>
<div class="page-header">
  <h1><%= link_to image_tag("universidad.png ")%><i>Cursos</i></h1>
</div>

<div class="row">
  <div class="span4">
    <%= form_tag request.path, :class => 'form-vertical', :method => 'get' do %>
      <%= content_tag :label, :class => 'control-label' do %>
      <h4>Bucar Cursos</h4>
          <%= text_field_tag :search, params[:search], :class => 'text_field' %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium', :name => nil %>
          <%= content_tag :label, :class => 'control-label' do %>
      <h4>Registros Mostrar</h4>
          <%= text_field_tag :registro, params[:registro], :class => 'text_field'  %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium'  %>
    </div>
    <% end %>
   <% end %>
  <% end %>   
</div>   

<table class="table table-bordered pretty ">
  <thead>
    <tr >
      <th><%= sortable "id" %></th>
      <th>Nombres</th>
      <th>fichas</th>
      <th>Instructor-Asignados</th>
    
       
    </tr>
  </thead>
  <tbody>
     <%= render @cursos %>
  </tbody>
  <tfoot>
    <tr>
      <td><%= link_to image_tag('nuevo.png', :tile  => "Mostrar Equipos"),  new_curso_path,  :remote => true %></td>
      
    </tr>
  </tfoot>
 <tfoot>
    <tr>
      <td>
    <b>Total Cursos</b>
  </td>
    <td>
    <%= @cursos.total_entries %>
  </td>
    </tr>
  </tfoot>
</table>
</div>
  <div align="center">
    <div class="pagination">
    </ul>
    <%= will_paginate @cursos, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  </div>
</div>

app/views/cursos/index.xls.erb
<h1>Lista de Cursos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Ficha</th>
    <th>Instructor_id</th>
    <th></th>
  </tr>
<% @cursos.each do |curso| %>
  <tr>
    <td><%= curso.nombre %></td>
    <td><%= curso.ficha %></td>
    <td><%= curso.instructor_id %></td>
  </tr>
<% end %>
</table>

app/views/cursos/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/cursos/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})
$('#cursos').tooltip('show')

app/views/cursos/update.js.erb
$('tr#curso_<%= @curso.id %>').replaceWith("<%= escape_javascript(render @curso) %>")
$.lazybox.close()