config/routes.rb
Escuela::Application.routes.draw do


  resources :ubicaciones

  resources :cursos do
  resources :estudiantes
  end
  get "pages/index"
  resources :studiantes
  resources :curso
  resources :pages
  resources :estudiante
  resources :horarios
  resources :materias
  resources :instructores
  root :to => 'pages#index'


 
end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :curso
  
    attr_accessible :cedula, :direccion, :email, :fcha_nacimineto, :nombre, :curso_id

    validates :nombre, :presence => true, :length => { :maximum => 40 }

	validates :email, :presence => true,
	:uniqueness => true, :format => { :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

	validates :cedula, :presence => true, :length => { :minimum => 10, :maximum => 15 },
	:numericality => true
        
	
    

    def self.search(search)
		where('nombre like ?', "%#{search}%")
	end
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_filter :find_curso_estudiantes

  def index

      @estudiantes = @curso.estudiante.order(sort_column + " " + sort_direction).search(params[:search]).page(params[:page]).per_page(2)
      respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @estudiantes }
    end
  end

  def show
  end

  def new
      @estudiante =  Estudiante.new
  end

  def edit
     
  end

  def create
      @estudiante = @curso.estudiante.build(params[:estudiante])
      render :action => :new unless @estudiante.save
  end

  def update
    render :action => :edit unless @estudiante.update_attributes(params[:estudiante])
  end

  def destroy
    @estudiante.destroy
  end

  private

  def find_curso_estudiantes
     @curso = Curso.find(params[:curso_id])
     @estudiante = Estudiante.find(params[:id]) if params[:id]
  end


  private

  def sort_column

   Estudiante.column_names.include?(params[:sort]) ? params[:sort] : "nombre"
    
  end

  def sort_direction 

    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    
  end
  
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
	def display_base_errors resource
return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
html = <<-HTML
<div class="alert alert-error alert-block">
<button type="button" class="close" data-dismiss="alert">&#215;</button>
#{messages}
</div>
HTML
html.html_safe
end
end

app/views/estudiantes/_estudiante.html.erb
<tr id=<%= "estudiante_#{estudiante.id}" %>
  <td></td>
  <td><%= estudiante.id %></td>
  <td><%= estudiante.nombre %></td>
  <td><%= estudiante.cedula %></td>
  <td><%= estudiante.email %></td>
  <td><%= estudiante.direccion %></td>
  <td><%= estudiante.fcha_nacimineto %></td>
  <td>
    <%= link_to 'Mostrar', curso_estudiante_path(@curso, estudiante), :remote => true, :class => 'btn btn-mini' %>
    <td>
    <%= link_to 'Editar', edit_curso_estudiante_path(@curso, estudiante), :remote => true,
        :class => 'btn btn-mini' %></td>
        <td>
    <%= link_to 'Eliminar', curso_estudiante_path(@curso, estudiante), 
        :data => { :confirm => 'Esta Seguro?' },
        :method => :delete, :remote => true, :class => 'btn btn-mini btn-danger' %></td>
      
  </td>
</tr>
  
         
            
             
  

app/views/estudiantes/_form.html.erb
<%= simple_form_for([@curso, @estudiante], :html => { :class => 'form-horizontal' },
 :remote => true) do |f| %>

  <%= f.error_notification %>
  <%= display_base_errors @estudiante %>

   <%= f.input :nombre %>
  <%= f.input :cedula %>
  <%= f.input :email %>
  <%= f.input :direccion %>
  <%= f.input :fcha_nacimineto %>
  
  
  <div class="form-actions">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
   <%= link_to 'Atras', curso_estudiantes_path, :class => 'btn btn-small' %>
  </div>
<% end %>

app/views/estudiantes/_show.html.erb
<%- model_class = Estudiante -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class='team'>
  <p><b>Id:</b> <%= @estudiante.id %></p>
  <p><b>Nombre:</b> <%= @estudiante.nombre %></p>
  <p><b>Cedula:</b> <%= @estudiante.cedula %></p>
  <p><b>Email:</b> <%= @estudiante.email %></p>
  <p><b>Direccion:</b> <%= @estudiante.direccion %></p>
  <p><b>Fecha Nacimiento:</b> <%= @estudiante.fcha_nacimineto %></p>

</div>

app/views/estudiantes/create.js.erb
$('table tbody').append("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()

app/views/estudiantes/destroy.js.erb
$("table tr#estudiante_<%= @estudiante.id %>").remove();

app/views/estudiantes/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true});

app/views/estudiantes/index.html.erb
<%- model_class = Estudiante -%>
  <div class="page-header">
    <h1><%= link_to image_tag("universidad.png")%><i><%= @curso.nombre %></i></h1>
  </div>    
<div class="row">
  <div class="span4">
    <%= form_tag request.path, :class => 'form-vertical', :method => 'get' do %>
      <%= content_tag :label, :class => 'control-label' do %>
      <h4>Bucar Estudiantes</h4>
          <%= text_field_tag :search, params[:search], :class => 'text_field' %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium', :name => nil %>
          <%= content_tag :label, :class => 'control-label' do %>
      <h4>Registros Mostrar</h4>
          <%= text_field_tag :registro, params[:registro], :class => 'text_field'  %>
          <%= submit_tag "Consultar", :class => 'btn btn-medium'  %>
    </div>
    <% end %>
   <% end %>
  <% end %>   
</div>
      <table class="table table-bordered pretty">
        <thead>
          <tr>
            <th><%=  sortable "id" %></th>
            <th>Nombres</th>
            <th>cedula</th>
            <th>email</th>
            <th>direccion</th>
            <th>fecha nacimiento</th>
           
          </tr>
        </thead>
        <tbody>
          <%= render @estudiantes %>
        </tbody>
          <tfoot>
            <tr>
              <td><%= link_to image_tag("participantes.png"), new_curso_estudiante_path, :remote => true  %> </td>
              <td><%= link_to image_tag("atras.png"), cursos_path %></td>
            </tr>
          </tfoot>
        <tfoot>
          <tr>
            <td><b>Total Aprendices</b>
            </td>
            <td><%= @estudiantes.total_entries %>
            </td>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="row">
    <div class="span2"> 
  </div>
  <div class="span10">
  
    <div class="pagination">
    </ul>
    <%= will_paginate @estudiantes, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente
    &raquo;' %>
  </ul>
  </div>
</div>
</div>

app/views/estudiantes/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>");

app/views/estudiantes/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})
$('#estudiantes').tooltip('show')

app/views/estudiantes/update.js.erb
$('tr#estudiante_<%= @estudiante.id %>').replaceWith("<%= escape_javascript(render @estudiante) %>")
$.lazybox.close()