config/routes.rb
Escuela::Application.routes.draw do


  resources :ubicaciones

  resources :cursos do
  resources :estudiantes
  end
  get "pages/index"
  resources :studiantes
  resources :curso
  resources :pages
  resources :estudiante
  resources :horarios
  resources :materias
  resources :instructores
  root :to => 'pages#index'


 
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
<a class="close" data-dismiss="alert">&#215;</a>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
<!-- if user_signed_in? %> -->
<li>
<li>
<%= link_to('Cursos', cursos_path) %>
</li>
<li>
<%= link_to('Horarios', horarios_path) %>
</li>
<!-- else %> -->
<li>
<%= link_to('Instructores', instructores_path) %>
</li>
<!-- end %> -->
<!-- if user_signed_in? %> -->
<li>
<%= link_to('Materias', materias_path) %>
</li>
<!-- else %> -->
<!-- end %> -->
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pagination" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>    
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    
  </head>
  <style type="text/css">
  body {  
    background-color: gray;    
  } 
  </style>
  <body>
   <header class="navbar navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
           <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
           </a>
           <%= link_to image_tag("principal.png "), root_path, :class => 'brand' %>
           <div class="nav-collapse">
                <%= render 'layouts/navigation' %>
           </div>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>